feat: community spend pool
InjectiveLabs/injective-ts pull request #208
Opened 2023-06-30 16:22 UTC by ivan-angjelkoski

### In This PR:
- Added fetchCommunitySpendPool transactions

2023-07-01 17:33 UTC, shane-moore requested changes

2023-07-01 17:33 UTC, shane-moore commented on packages/sdk-ts/src/client/indexer/types/explorer-rest.ts
> +export interface BankTransfer {
can you move `BankTransfer` to `sdk-ts/src/client/indexer/types/explorer.ts`?

also, let's use `import { Coin } from '@injectivelabs/ts-types'` to replace the `{ denom: string; amount: string }`

2023-07-01 17:33 UTC, shane-moore commented on packages/sdk-ts/src/client/indexer/types/explorer-rest.ts
> +  amounts: { denom: string; amount: string }[]
let's use `import { Coin } from '@injectivelabs/ts-types'` to replace the `{ denom: string; amount: string }`

2023-07-02 21:33 UTC, bangjelkoski requested changes

2023-07-02 21:33 UTC, bangjelkoski commented on packages/sdk-ts/src/client/indexer/rest/IndexerRestExplorerApi.ts
> +  async fetchCommunitySpendPool(params: {
Nope, we should have `fetchBankTransfers` and then pass the `is_community_pool_related` as a parameter on the function call.

2023-07-02 21:35 UTC, bangjelkoski commented on packages/sdk-ts/src/client/indexer/rest/IndexerRestExplorerApi.ts
> +  async fetchCommunitySpendPool(params: {
I've resolved it.

2023-07-02 21:35 UTC, merged